names:
- cancer
nc: 1
train: /home/quynhlx@kaopiz.local/Documents/Lung-cancer/datasets/cancer_detection_aug/images
val: /home/quynhlx@kaopiz.local/Documents/Lung-cancer/datasets/cancer_detection/images
